export const standings = [
	{ pos: 1, name: "Player 1", team: "Team B", score: 92 },
	{ pos: 2, name: "Player 2", team: "Team C", score: 28 },
	{ pos: 3, name: "Player 3", team: "Team D", score: 93 },
	{ pos: 4, name: "Player 4", team: "Team A", score: 43 },
	{ pos: 5, name: "Player 5", team: "Team D", score: 86 },
	{ pos: 6, name: "Player 6", team: "Team B", score: 55 },
	{ pos: 7, name: "Player 7", team: "Team B", score: 0 },
	{ pos: 8, name: "Lorenzo Ferretti", team: "Team C", score: 6 },
	{ pos: 9, name: "Player 9", team: "Team A", score: 72 },
	{ pos: 10, name: "Player 10", team: "Team B", score: 1 },
	{ pos: 11, name: "Player 11", team: "Team C", score: 3 },
	{ pos: 12, name: "Player 12", team: "Team A", score: 3 },
	{ pos: 13, name: "Player 13", team: "Team B", score: 2 },
	{ pos: 14, name: "Player 14", team: "Team B", score: 6 },
	{ pos: 15, name: "Player 15", team: "Team B", score: 3 },
	{ pos: 16, name: "Player 16", team: "Team C", score: 2 },
	{ pos: 17, name: "Player 17", team: "Team B", score: 2 },
	{ pos: 18, name: "Player 18", team: "Team C", score: 1 },
	{ pos: 19, name: "Player 19", team: "Team D", score: 4 },
	{ pos: 20, name: "Player 20", team: "Team D", score: 4 },
];

export const liveStandings = [
	{ name: "Player 1", team: "Team B", score: 920 },
	{ name: "Player 2", team: "Team C", score: 898 },
	{ name: "Player 3", team: "Team D", score: 883 },
	{ name: "Player 4", team: "Team A", score: 843 },
	{ name: "Player 5", team: "Team D", score: 826 },
	{ name: "Player 6", team: "Team B", score: 815 },
	{ name: "Player 7", team: "Team B", score: 800 },
	{ name: "Lorenzo Ferretti", team: "Team C", score: 797 },
	{ name: "Player 9", team: "Team A", score: 772 },
	{ name: "Player 10", team: "Team B", score: 761 },
	{ name: "Player 11", team: "Team C", score: 753 },
	{ name: "Player 12", team: "Team A", score: 743 },
	{ name: "Player 13", team: "Team B", score: 722 },
	{ name: "Player 14", team: "Team B", score: 696 },
	{ name: "Player 15", team: "Team B", score: 673 },
	{ name: "Player 16", team: "Team C", score: 642 },
	{ name: "Player 17", team: "Team B", score: 622 },
	{ name: "Player 18", team: "Team C", score: 611 },
	{ name: "Player 19", team: "Team D", score: 604 },
	{ name: "Player 20", team: "Team D", score: 604 },
];
