export const GET_FANTATEAM = "GET_FANTATEAM";
export const GET_FANTATEAM_ERROR = "GET_FANTATEAM_ERROR";
export const CREATE_FANTATEAM = "CREATE_FANTATEAM";
export const CREATE_FANTATEAM_ERROR = "CREATE_FANTATEAM_ERROR";
